/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "cla_4bit.v:1.1-28.10" *)
module cla_4bit(A, B, Cin, Sum, Cout);
  (* src = "cla_4bit.v:17.21-17.31" *)
  wire _00_;
  (* src = "cla_4bit.v:18.21-18.30" *)
  wire _01_;
  (* src = "cla_4bit.v:19.21-19.30" *)
  wire _02_;
  (* src = "cla_4bit.v:20.23-20.32" *)
  wire _03_;
  (* src = "cla_4bit.v:2.17-2.18" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "cla_4bit.v:3.17-3.18" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "cla_4bit.v:4.11-4.14" *)
  input Cin;
  wire Cin;
  (* src = "cla_4bit.v:6.12-6.16" *)
  output Cout;
  wire Cout;
  (* src = "cla_4bit.v:9.12-9.13" *)
  wire [3:0] G;
  (* src = "cla_4bit.v:9.15-9.16" *)
  wire [3:0] P;
  (* src = "cla_4bit.v:5.18-5.21" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  (* src = "cla_4bit.v:10.6-10.8" *)
  wire c1;
  (* src = "cla_4bit.v:10.10-10.12" *)
  wire c2;
  (* src = "cla_4bit.v:10.14-10.16" *)
  wire c3;
  assign G = A & (* src = "cla_4bit.v:13.12-13.17" *) B;
  assign _00_ = P[0] & (* src = "cla_4bit.v:17.21-17.31" *) Cin;
  assign _01_ = P[1] & (* src = "cla_4bit.v:18.21-18.30" *) c1;
  assign _02_ = P[2] & (* src = "cla_4bit.v:19.21-19.30" *) c2;
  assign _03_ = P[3] & (* src = "cla_4bit.v:20.23-20.32" *) c3;
  assign c1 = G[0] | (* src = "cla_4bit.v:17.13-17.32" *) _00_;
  assign c2 = G[1] | (* src = "cla_4bit.v:18.13-18.31" *) _01_;
  assign c3 = G[2] | (* src = "cla_4bit.v:19.13-19.31" *) _02_;
  assign Cout = G[3] | (* src = "cla_4bit.v:20.15-20.33" *) _03_;
  assign P = A ^ (* src = "cla_4bit.v:14.12-14.17" *) B;
  assign Sum[0] = P[0] ^ (* src = "cla_4bit.v:23.17-23.27" *) Cin;
  assign Sum[1] = P[1] ^ (* src = "cla_4bit.v:24.17-24.26" *) c1;
  assign Sum[2] = P[2] ^ (* src = "cla_4bit.v:25.17-25.26" *) c2;
  assign Sum[3] = P[3] ^ (* src = "cla_4bit.v:26.17-26.26" *) c3;
endmodule
