/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* top =  1  *)
(* src = "rca_4bit.v:1.1-43.10" *)
module rca_4bit(A, B, Cin, Sum, Cout);
  (* src = "full_adder.v:10.16-10.21" *)
  wire _00_;
  (* src = "full_adder.v:10.26-10.33" *)
  wire _01_;
  (* src = "full_adder.v:10.38-10.45" *)
  wire _02_;
  (* src = "full_adder.v:10.15-10.34" *)
  wire _03_;
  (* src = "full_adder.v:9.15-9.20" *)
  wire _04_;
  (* src = "full_adder.v:10.16-10.21" *)
  wire _05_;
  (* src = "full_adder.v:10.26-10.33" *)
  wire _06_;
  (* src = "full_adder.v:10.38-10.45" *)
  wire _07_;
  (* src = "full_adder.v:10.15-10.34" *)
  wire _08_;
  (* src = "full_adder.v:9.15-9.20" *)
  wire _09_;
  (* src = "full_adder.v:10.16-10.21" *)
  wire _10_;
  (* src = "full_adder.v:10.26-10.33" *)
  wire _11_;
  (* src = "full_adder.v:10.38-10.45" *)
  wire _12_;
  (* src = "full_adder.v:10.15-10.34" *)
  wire _13_;
  (* src = "full_adder.v:9.15-9.20" *)
  wire _14_;
  (* src = "full_adder.v:10.16-10.21" *)
  wire _15_;
  (* src = "full_adder.v:10.26-10.33" *)
  wire _16_;
  (* src = "full_adder.v:10.38-10.45" *)
  wire _17_;
  (* src = "full_adder.v:10.15-10.34" *)
  wire _18_;
  (* src = "full_adder.v:9.15-9.20" *)
  wire _19_;
  (* src = "rca_4bit.v:2.18-2.19" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "rca_4bit.v:3.18-3.19" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "rca_4bit.v:4.12-4.15" *)
  input Cin;
  wire Cin;
  (* src = "rca_4bit.v:6.12-6.16" *)
  output Cout;
  wire Cout;
  (* hdlname = "FA0 a" *)
  (* src = "full_adder.v:2.11-2.12" *)
  wire \FA0.a ;
  (* hdlname = "FA0 b" *)
  (* src = "full_adder.v:3.11-3.12" *)
  wire \FA0.b ;
  (* hdlname = "FA0 cin" *)
  (* src = "full_adder.v:4.11-4.14" *)
  wire \FA0.cin ;
  (* hdlname = "FA0 cout" *)
  (* src = "full_adder.v:6.12-6.16" *)
  wire \FA0.cout ;
  (* hdlname = "FA0 sum" *)
  (* src = "full_adder.v:5.12-5.15" *)
  wire \FA0.sum ;
  (* hdlname = "FA1 a" *)
  (* src = "full_adder.v:2.11-2.12" *)
  wire \FA1.a ;
  (* hdlname = "FA1 b" *)
  (* src = "full_adder.v:3.11-3.12" *)
  wire \FA1.b ;
  (* hdlname = "FA1 cin" *)
  (* src = "full_adder.v:4.11-4.14" *)
  wire \FA1.cin ;
  (* hdlname = "FA1 cout" *)
  (* src = "full_adder.v:6.12-6.16" *)
  wire \FA1.cout ;
  (* hdlname = "FA1 sum" *)
  (* src = "full_adder.v:5.12-5.15" *)
  wire \FA1.sum ;
  (* hdlname = "FA2 a" *)
  (* src = "full_adder.v:2.11-2.12" *)
  wire \FA2.a ;
  (* hdlname = "FA2 b" *)
  (* src = "full_adder.v:3.11-3.12" *)
  wire \FA2.b ;
  (* hdlname = "FA2 cin" *)
  (* src = "full_adder.v:4.11-4.14" *)
  wire \FA2.cin ;
  (* hdlname = "FA2 cout" *)
  (* src = "full_adder.v:6.12-6.16" *)
  wire \FA2.cout ;
  (* hdlname = "FA2 sum" *)
  (* src = "full_adder.v:5.12-5.15" *)
  wire \FA2.sum ;
  (* hdlname = "FA3 a" *)
  (* src = "full_adder.v:2.11-2.12" *)
  wire \FA3.a ;
  (* hdlname = "FA3 b" *)
  (* src = "full_adder.v:3.11-3.12" *)
  wire \FA3.b ;
  (* hdlname = "FA3 cin" *)
  (* src = "full_adder.v:4.11-4.14" *)
  wire \FA3.cin ;
  (* hdlname = "FA3 cout" *)
  (* src = "full_adder.v:6.12-6.16" *)
  wire \FA3.cout ;
  (* hdlname = "FA3 sum" *)
  (* src = "full_adder.v:5.12-5.15" *)
  wire \FA3.sum ;
  (* src = "rca_4bit.v:5.18-5.21" *)
  output [3:0] Sum;
  wire [3:0] Sum;
  (* src = "rca_4bit.v:9.6-9.8" *)
  wire c1;
  (* src = "rca_4bit.v:9.10-9.12" *)
  wire c2;
  (* src = "rca_4bit.v:9.14-9.16" *)
  wire c3;
  assign _00_ = A[0] & (* src = "full_adder.v:10.16-10.21" *) B[0];
  assign _01_ = B[0] & (* src = "full_adder.v:10.26-10.33" *) Cin;
  assign _02_ = A[0] & (* src = "full_adder.v:10.38-10.45" *) Cin;
  assign _03_ = _00_ | (* src = "full_adder.v:10.15-10.34" *) _01_;
  assign \FA1.cin  = _03_ | (* src = "full_adder.v:10.15-10.46" *) _02_;
  assign _04_ = A[0] ^ (* src = "full_adder.v:9.15-9.20" *) B[0];
  assign \FA0.sum  = _04_ ^ (* src = "full_adder.v:9.15-9.26" *) Cin;
  assign _05_ = A[1] & (* src = "full_adder.v:10.16-10.21" *) B[1];
  assign _06_ = B[1] & (* src = "full_adder.v:10.26-10.33" *) \FA1.cin ;
  assign _07_ = A[1] & (* src = "full_adder.v:10.38-10.45" *) \FA1.cin ;
  assign _08_ = _05_ | (* src = "full_adder.v:10.15-10.34" *) _06_;
  assign \FA2.cin  = _08_ | (* src = "full_adder.v:10.15-10.46" *) _07_;
  assign _09_ = A[1] ^ (* src = "full_adder.v:9.15-9.20" *) B[1];
  assign \FA1.sum  = _09_ ^ (* src = "full_adder.v:9.15-9.26" *) \FA1.cin ;
  assign _10_ = A[2] & (* src = "full_adder.v:10.16-10.21" *) B[2];
  assign _11_ = B[2] & (* src = "full_adder.v:10.26-10.33" *) \FA2.cin ;
  assign _12_ = A[2] & (* src = "full_adder.v:10.38-10.45" *) \FA2.cin ;
  assign _13_ = _10_ | (* src = "full_adder.v:10.15-10.34" *) _11_;
  assign \FA3.cin  = _13_ | (* src = "full_adder.v:10.15-10.46" *) _12_;
  assign _14_ = A[2] ^ (* src = "full_adder.v:9.15-9.20" *) B[2];
  assign \FA2.sum  = _14_ ^ (* src = "full_adder.v:9.15-9.26" *) \FA2.cin ;
  assign _15_ = A[3] & (* src = "full_adder.v:10.16-10.21" *) B[3];
  assign _16_ = B[3] & (* src = "full_adder.v:10.26-10.33" *) \FA3.cin ;
  assign _17_ = A[3] & (* src = "full_adder.v:10.38-10.45" *) \FA3.cin ;
  assign _18_ = _15_ | (* src = "full_adder.v:10.15-10.34" *) _16_;
  assign Cout = _18_ | (* src = "full_adder.v:10.15-10.46" *) _17_;
  assign _19_ = A[3] ^ (* src = "full_adder.v:9.15-9.20" *) B[3];
  assign \FA3.sum  = _19_ ^ (* src = "full_adder.v:9.15-9.26" *) \FA3.cin ;
  assign \FA0.a  = A[0];
  assign \FA0.b  = B[0];
  assign \FA0.cin  = Cin;
  assign \FA0.cout  = \FA1.cin ;
  assign \FA1.a  = A[1];
  assign \FA1.b  = B[1];
  assign \FA1.cout  = \FA2.cin ;
  assign \FA2.a  = A[2];
  assign \FA2.b  = B[2];
  assign \FA2.cout  = \FA3.cin ;
  assign \FA3.a  = A[3];
  assign \FA3.b  = B[3];
  assign \FA3.cout  = Cout;
  assign Sum = { \FA3.sum , \FA2.sum , \FA1.sum , \FA0.sum  };
  assign c1 = \FA1.cin ;
  assign c2 = \FA2.cin ;
  assign c3 = \FA3.cin ;
endmodule
